import type { NextPage } from "next";
import Head from "next/head";
import Img from "next/image";

import { trpc } from "../utils/trpc";

const Home: NextPage = () => {
  const { data } = trpc.useQuery(["football.get-teams"]);

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex flex-col w-1/2 min-h-screen mx-auto">
        <h1 className="font-extrabold text-center text-7xl">
          Create <span className="text-blue-500">T3</span> App
        </h1>

        <div className="w-fit">
          {data && (
            <ul>
              {data.map((t) => {
                return (
                  <li className="pb-4" key={`team-${t.id}`}>
                    <div className="flex items-center">
                      <Img src={t.logo} alt={t.name} width={32} height={32} />
                      <div className="mr-4" />
                      <h3 className="text-xl">{t.name}</h3>
                    </div>
                  </li>
                );
              })}
            </ul>
          )}
        </div>
      </div>
    </>
  );
};

export default Home;
